# Generated by Django 4.2.6 on 2023-11-25 16:05

from django.db import migrations

def add_default_categories(apps, schema_editor):
    Category = apps.get_model('ExpenseTracker', 'Category') 
    Category.objects.create(name='Clothes')
    Category.objects.create(name='Transport')
    Category.objects.create(name='Others')


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseTracker', '0002_userprofile'),
    ]

    operations = [
         migrations.RunPython(add_default_categories),
    ]


